server:
  port: 9091

spring:
  application:
    name: auctions
  profiles:
    active: #spring.profiles.active#
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    database-change-log-lock-table: DATABASECHANGELOGLOCK
    database-change-log-table: DATABASECHANGELOG
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://bksoftwarevn.com:6633/auctions_system?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: auctions_system
    password: auctions_system2022
    hikari:
      poolName: Hikari
      auto-commit: false
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    show-sql: false
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
springdoc:
  swagger-ui:
    path: /docs.html
    operationsSorter: method
  api-docs:
    path: /docs
