openapi: 3.0.3

info:
  title: Auctions Account API Spec
  description: Specs for Auctions Account API
  version: 1.0.0
  x-icon: auctions

servers:
  - description: local test
    url: http://localhost:8080/api/account/v1
  - description: prod test
    url: https://auctions.bksoftwarevn.com/api/account/v1

tags:
  - name: Account

paths:

  /api/account/v1/info:
    description: Get the current user.
    get:
      summary: Get request to get current account infomation
      description: request to get current user
      operationId: getAccount
      responses:
        "200":
          $ref: 'common.yaml#/components/responses/UserInfoResponse'
      tags:
        - Account
  /api/account/v1/edit:
    description: Update user
    post:
      summary: Post update user infomation
      description: request to update user infomation
      operationId: postUpdateAccount
      requestBody:
        description: update user request body
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/user/update-user-request.yaml'
      responses:
        "200":
          $ref: 'common.yaml#/components/responses/UpdateUserResponse'
      tags:
        - Account
  /api/account/v1/change-password:
    description: Update password
    post:
      summary: Post update my password
      description: request to update password
      operationId: postChangePassword
      requestBody:
        description: update pasword body
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/user/change-password-request.yaml'
      responses:
        "200":
          $ref: 'common.yaml#/components/responses/ChangePasswordResponse'
      tags:
        - Account
  /api/account/v1/logout:
    description: Logout
    post:
      summary: Post logout
      description: request to logout
      operationId: postLogoutAccount
      responses:
        "200":
          $ref: 'common.yaml#/components/responses/CommonResponse'
      tags:
        - Account
  /api/account/v1/contact-us:
    description: Send request to admin user
    post:
      summary: Post request to admin user
      description: request to send infomation to admin user
      operationId: contactUs
      requestBody:
        description: request infomation request body
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: 'schemas/user/contact-us-request.yaml'
      responses:
        "200":
          $ref: 'common.yaml#/components/responses/CommonResponse'
      tags:
        - Account