openapi: 3.0.3

info:
  title: Auctions Client API Spec
  description: Specs for Auctions Client API
  version: 1.0.0
  x-icon: auctions

servers:
  - description: local test
    url: http://localhost:8080/api/client/v1
  - description: prod test
    url: https://auctions.bksoftwarevn.com/api/client/v1

tags:
  - name: Client

paths:

  /api/client/v1/lockOrUnlock:
    description: Lock & Unlock Users
    post:
      summary: Post request to lock or unlock user by cif
      description: request to lock or unlock user by cif
      operationId: postLockOrUnlock'
      requestBody:
        description: lock or unlock request
        content:
          application/json:
            schema:
              $ref: 'schemas/lock-unlock-request.yaml'
      responses:
        "200":
          $ref: 'common.yaml#/components/responses/LockOrUnlockResponse'
      tags:
        - integration
  /api/client/v1/demographic:
    description: Demographic
    post:
      summary: Post request to get demographic user by cif
      description: request to get demographic user by cif
      operationId: postDemographic'
      requestBody:
        description: demographic request
        content:
          application/json:
            schema:
              $ref: 'schemas/demographic-request.yaml'
      responses:
        "200":
          $ref: 'common.yaml#/components/responses/DemographicResponse'
      tags:
        - client