openapi: 3.0.3

info:
  title: OpenAPI Common
  description: Common items to use in schemas.
  version: 3.0.3

paths: { }

components:

  parameters:

    IdPathParam:
      name: id
      description: ID
      in: query
      required: true
      schema:
        type: string

  responses:
    UserRegisterResponse:
      description: User register successful response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserRegisterResponse'
    UpdateUserResponse:
      description: Update user successful response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateUserResponse'
    AuthenResponse:
      description: Authenticate response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthenResponse'
    ActiveUserResponse:
      description: Active user response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ActiveUserResponse'
    AccountResponse:
      description: Account info
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserItem'
    ChangePasswordResponse:
      description: Change password response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ChangePasswordResponse'
    CommonResponse:
      description: Change password response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CommonResponse'
    UserInfoResponse:
      description: User info response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserRegisterResponse'
    CreateCategoryGroupResponse:
      description: Create category response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateCategoryGroupResponse'
    GroupsResponse:
      description: list group response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GroupsResponse'
    CreateRoleResponse:
      description: list group response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateRoleResponse'
    RolesResponse:
      description: list role response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RolesResponse'
    CategoriesResponse:
      description: list category response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CategoriesResponse'
    CreateCategoryResponse:
      description: list category response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateCategoryResponse'
    CreateAuctionResponse:
      description: create auction response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateAuctionResponse'
    AuctionsResponse:
      description: list auction response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuctionsResponse'
    FilterAuctionResponse:
      description: filter auction response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FilterAuctionResponse'
    DetailAuctionResponse:
      description: detail auction response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DetailAuctionResponse'
    AuctionInfoResponse:
      description: info auction response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuctionInfoResponse'
    CreateProductResponse:
      description: create product response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateProductResponse'
    CreateBrandResponse:
      description: create brand response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateBrandResponse'
    BrandsResponse:
      description: get list brand response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BrandsResponse'
    CreateCommentResponse:
      description: create comment response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateCommentResponse'
    CommentsResponse:
      description: get list comments response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CommentsResponse'
    CreateBidResponse:
      description: create bid response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateBidResponse'
    BidsResponse:
      description: get list bid response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BidsResponse'
    AcceptedBidResponse:
      description: accepted bid response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AcceptedBidResponse'
    CreateLikeResponse:
      description: like response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateLikeResponse'
    AuctionsLikedResponse:
      description: auctions liked response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuctionsLikedResponse'
    TotalLikedResponse:
      description: total auctions liked response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TotalLikedResponse'
    CreateNewsResponse:
      description: create news response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateNewsResponse'
    SearchNewsResponse:
      description: search news response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SearchNewsResponse'
    SearchNotificationsResponse:
      description: search notifications response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SearchNotificationsResponse'
    DetailNotificationsResponse:
      description: detail notifications response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DetailNotificationsResponse'
    SearchAuctionResponse:
      description: search auctions response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SearchAuctionResponse'

  schemas:
    CommonResponse:
      $ref: 'schemas/common-response.yaml'
    UserRegisterResponse:
      $ref: 'schemas/user/user-register-response.yaml'
    UpdateUserResponse:
      $ref: 'schemas/user/user-register-response.yaml'
    AuthenResponse:
      $ref: 'schemas/auth/authen-response.yaml'
    ActiveUserResponse:
      $ref: 'schemas/auth/active-response.yaml'
    UserItem:
      $ref: 'schemas/user/user-data-item.yaml'
    RoleItem:
      $ref: 'schemas/role/role-item.yaml'
    GroupItem:
      $ref: 'schemas/category/group-item.yaml'
    Category:
      $ref: 'schemas/category/category-item.yaml'
    AutionItem:
      $ref: 'schemas/auction/auction-item.yaml'

    ChangePasswordResponse:
      $ref: 'schemas/user/change-password-response.yaml'
    CreateCategoryGroupResponse:
      $ref: 'schemas/category/create-category-group-response.yaml'
    GroupsResponse:
      $ref: 'schemas/category/groups-response.yaml'
    CreateRoleResponse:
      $ref: 'schemas/role/create-role-response.yaml'
    RolesResponse:
      $ref: 'schemas/role/roles-response.yaml'
    AuctionsResponse:
      $ref: 'schemas/auction/auctions-response.yaml'
    SearchAuctionResponse:
      $ref: 'schemas/auction/search-auction-response.yaml'
    CategoriesResponse:
      $ref: 'schemas/category/categories-response.yaml'
    CreateCategoryResponse:
      $ref: 'schemas/category/create-category-response.yaml'
    CreateAuctionResponse:
      $ref: 'schemas/auction/create-auction-response.yaml'
    FilterAuctionResponse:
      $ref: 'schemas/auction/filter-auction-response.yaml'
    DetailAuctionResponse:
      $ref: 'schemas/auction/detail-auction-response.yaml'
    AuctionInfoResponse:
      $ref: 'schemas/auction/info-auction-response.yaml'
    CreateProductResponse:
      $ref: 'schemas/product/create-product-response.yaml'
    CreateBrandResponse:
      $ref: 'schemas/brand/create-brand-response.yaml'
    BrandsResponse:
      $ref: 'schemas/brand/brands-response.yaml'
    CreateCommentResponse:
      $ref: 'schemas/comment/create-comment-response.yaml'
    CommentsResponse:
      $ref: 'schemas/comment/comments-response.yaml'
    CreateBidResponse:
      $ref: 'schemas/bid/create-bid-response.yaml'
    BidsResponse:
      $ref: 'schemas/bid/bids-response.yaml'
    AcceptedBidResponse:
      $ref: 'schemas/bid/accept-bid-response.yaml'
    CreateLikeResponse:
      $ref: 'schemas/comment/create-like-response.yaml'
    AuctionsLikedResponse:
      $ref: 'schemas/comment/search-auctions-liked-response.yaml'
    TotalLikedResponse:
      $ref: 'schemas/comment/total-like-response.yaml'
    CreateNewsResponse:
      $ref: 'schemas/news/create-news-response.yaml'
    SearchNewsResponse:
      $ref: 'schemas/news/search-news-response.yaml'
    SearchNotificationsResponse:
      $ref: 'schemas/noti/search-notifications-response.yaml'
    DetailNotificationsResponse:
      $ref: 'schemas/noti/detail-notifications-response.yaml'