openapi: 3.0.3

info:
  title: OpenAPI Common
  description: Common items to use in schemas.
  version: 3.0.3

paths: { }

components:
  responses:
    UserRegisterResponse:
      description: User register successful response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserRegisterResponse'
    UpdateUserResponse:
      description: Update user successful response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateUserResponse'
    AuthenResponse:
      description: Authenticate response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthenResponse'
    ActiveUserResponse:
      description: Active user response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ActiveUserResponse'
    AccountResponse:
      description: Account info
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserItem'
    ChangePasswordResponse:
      description: Change password response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ChangePasswordResponse'
    CommonResponse:
      description: Change password response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CommonResponse'
    UserInfoResponse:
      description: User info response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserRegisterResponse'
    CreateCategoryGroupResponse:
      description: Create category response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateCategoryGroupResponse'
    GroupsResponse:
      description: list group response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GroupsResponse'
    CreateRoleResponse:
      description: list group response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateRoleResponse'
    RolesResponse:
      description: list role response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RolesResponse'

  schemas:
    CommonResponse:
      $ref: 'schemas/common-response.yaml'
    UserRegisterResponse:
      $ref: 'schemas/user/user-register-response.yaml'
    UpdateUserResponse:
      $ref: 'schemas/user/user-register-response.yaml'
    AuthenResponse:
      $ref: 'schemas/auth/authen-response.yaml'
    ActiveUserResponse:
      $ref: 'schemas/auth/active-response.yaml'
    UserItem:
      $ref: 'schemas/user/user-data-item.yaml'
    RoleItem:
      $ref: 'schemas/user/role-item.yaml'
    GroupItem:
      $ref: 'schemas/category/group-item.yaml'
    ChangePasswordResponse:
      $ref: 'schemas/user/change-password-response.yaml'
    CreateCategoryGroupResponse:
      $ref: 'schemas/category/create-category-group-response.yaml'
    GroupsResponse:
      $ref: 'schemas/category/groups-response.yaml'
    CreateRoleResponse:
      $ref: 'schemas/role/create-role-response.yaml'
    RolesResponse:
      $ref: 'schemas/role/roles-response.yaml'